# **Project 1 - Sales Analysis - ETL**

## Objectives

- Extract data from provided CSV files
- Clean it 
- Apply feature engineering if necessary 
- Remove any unnecessary columns
- Save to a new CSV file


## Inputs

CSV files provided:

stores data-set.csv
sales data-set.csv
features data set.csv

Renamed files to a uniform naming convention:

Sales_Features_DataSet.csv
Sales_DataSet.csv
Sales_Stores_DataSet.csv

Note: original files are stored in Data/OriginalFiles


## Outputs

CSV file created from ETL etc stored in Data/CleanedDataSets:

Sales_Stores_DataSet_Cleaned.csv



## Additional Comments

Had an error trying to use pip install - r requirements.txt 

So manually installed:

numpy
pandas
seaborn
plotly
seaborn
matplotlib

Will install any more required libraries as discovered...

Error:

(.venv) rogerwilliams@Rogers-iMac Project1-SalesAnalysis % pip install -r requirements.txt
Collecting numpy==1.26.1 (from -r requirements.txt (line 1))
  Using cached numpy-1.26.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting pandas==2.1.1 (from -r requirements.txt (line 2))
  Using cached pandas-2.1.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (18 kB)
Collecting matplotlib==3.8.0 (from -r requirements.txt (line 3))
  Using cached matplotlib-3.8.0-cp312-cp312-macosx_10_12_x86_64.whl.metadata (5.8 kB)
Collecting seaborn==0.13.2 (from -r requirements.txt (line 4))
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting ydata-profiling==4.12.0 (from -r requirements.txt (line 5))
  Using cached ydata_profiling-4.12.0-py2.py3-none-any.whl.metadata (20 kB)
Collecting plotly==5.17.0 (from -r requirements.txt (line 6))
  Using cached plotly-5.17.0-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting ppscore==1.1.0 (from -r requirements.txt (line 7))
  Using cached ppscore-1.1.0.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/rogerwilliams/Projects/Python/CourseProjects/Project1-SalesAnalysis/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/rogerwilliams/Projects/Python/CourseProjects/Project1-SalesAnalysis/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/rogerwilliams/Projects/Python/CourseProjects/Project1-SalesAnalysis/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wv/yty584vs1kq76d7zd3rv5wpw0000gn/T/pip-build-env-4o10ho_h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wv/yty584vs1kq76d7zd3rv5wpw0000gn/T/pip-build-env-4o10ho_h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wv/yty584vs1kq76d7zd3rv5wpw0000gn/T/pip-build-env-4o10ho_h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/wv/yty584vs1kq76d7zd3rv5wpw0000gn/T/pip-build-env-4o10ho_h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'pkg_resources'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

Note: This error originates from a subprocess, and is likely not a problem with pip.

## Initalise Working Environment

In [2]:
#import libraries
import os
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

# Section 1 - Initalisation

## Intitialise all variables to be used in global stack

In [3]:

#DataFrame vars for ETL
dfSales_Stores_DataSet = None
dfSales_Stores_DataSet_Work = None
dfCleaned = None
dfCheck = None

#missing values check vars
intMissing = 0
intMissingPercent = 0
intLessThanZero = 0
dfCheck = None

#duplicates check vars
intDuplicates = 0

#stores current directory
strCurrentDir = ""

#constant for project directory
CNST_STR_PROJECT_DIR = "Project1-SalesAnalysis"

#file path constants
CNST_STR_CLEANFILEPATH = "/Data/CleanedDataSets/Sales_Stores_DataSet_Cleaned.csv"
CNST_STR_SALESSTORESFILEPATH = "/Data/Sales_Stores_DataSet.csv"

#other vars
objColumns = None
lstColumns = []

## Set Current Directory To Base Project Directory

In [4]:
#get project directory - default is jupyter notebook sub folder as that is where this file is located!
#so move back one to the project root path
# Source - https://stackoverflow.com/a/17726833
# Posted by chimpsarehungry
# Retrieved 2026-07-05, License - CC BY-SA 3.0

#get current folder
strCurrentDir = os.getcwd()

#is the last part of the path the project directory?
if not strCurrentDir.endswith(CNST_STR_PROJECT_DIR):
   #get current working directory and move back one to the project root path
   strCurrentDir =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
   os.chdir(os.path.dirname(strCurrentDir))
   #change directory
   os.chdir(strCurrentDir)

#confirm current directory is project directory
print(f"Current Directory: \n {os.getcwd()}")

Current Directory:
 /Users/rogerwilliams/Projects/Python/CourseProjects/Project1-SalesAnalysis

# Section 1 - Extraction

- Read csv files
- Get schema info -> column and row numbers
- Get first 5 records
- Get list of column datatypes
- Get detailed schema infomation

## Read csv Files Into Variable For Processing

In [5]:
#read csv file into DataFrame
dfSales_Stores_DataSet = pd.read_csv(strCurrentDir + CNST_STR_SALESSTORESFILEPATH)

## Get Schema Info - Sales_Stores_DataSet

In [6]:
print(f"Schema Information \n Rows: {dfSales_Stores_DataSet.shape[0]} Columns: {dfSales_Stores_DataSet.shape[1]}")
dfSales_Stores_DataSet.head()

Schema Information
 Rows: 45 Columns: 3

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

## Observations - Sales_Stores_DataSet
45 rows
3 columns

Columns:

Store, Type, Size

In [7]:
#get column data types
print (f"Data Types: \n{dfSales_Stores_DataSet.dtypes}")

Data Types:
Store    int64
Type       str
Size     int64
dtype: object

In [8]:
#get schema infomation
print(f"More Information:\n {dfSales_Stores_DataSet.info()}")

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     str
 2   Size    45 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.2 KB
More Information:
 None

## Observations - Sales_Stores_DataSet

No missing values
File size: 1.2 KB

---

# Section 2 - Transformation

- Get missing values percent
- Get duplicates (if any)
- Convert Date column to datetime format

In [9]:
#get total missing values
intMissing = dfSales_Stores_DataSet.isnull().sum()

#calculate percent missing
intMissingPercent = ( intMissing / len(dfSales_Stores_DataSet) * 100)
dfCheck = pd.DataFrame( {"Missing Values": intMissing, "%" : intMissingPercent})

#show results
if dfCheck["Missing Values"].sum() !=0:
   print( dfCheck[dfCheck["Missing Values"] > 0])
else:
   print( "No Missing Values")

No Missing Values

## Observations - Sales_Stores_DataSet

No missing values!

## Find Duplicates - Sales_Stores_DataSet

In [10]:
#get number of duplicates
intDuplicates = dfSales_Stores_DataSet.isnull().sum()
intDuplicates

Store    0
Type     0
Size     0
dtype: int64

## Observations - Sales_Stores_DataSet

No duplicates!

## Get Unique Values - Sales_Stores_DataSet

In [11]:
#show unique values count
dfSales_Stores_DataSet.nunique()

Store    45
Type      3
Size     40
dtype: int64

## Observations - Sales_DataSet

Store has 45 unique values  
Type has 3 unique values  
Size has 40 unique values

## Get Categorical Value Distribution

In [12]:
#get categorical distribution for object columns (non numeric)
for objColumn in ["Type"]:
    print( f"[{objColumn}] Value Distribution:")
    print( dfSales_Stores_DataSet[objColumn].value_counts())

[Type] Value Distribution:
Type
A    22
B    17
C     6
Name: count, dtype: int64

## Observations - Sales_DataSet

No deviations as the column data is just A or B or C

In [13]:
## Create Copy Of DataFrame
dfSales_Stores_DataSet_Work = dfSales_Stores_DataSet.copy()

## Strip Spaces From Type Column

In [15]:
#remove spaces from type column (string datatype)
for objColumn in["Type"]:
    dfSales_Stores_DataSet_Work[objColumn] = dfSales_Stores_DataSet_Work[objColumn].str.strip()
    
#show first 5 rows to check    
dfSales_Stores_DataSet_Work.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

## Observations - Sales_Stores_DataSet

No data corruptions

## Observations - Sales_Stores_DataSet

Date is a string - needs conversion to datetime
Other column types look ok

## Observations - Sales_Stores_DataSet

Conversion looks successful

## Validate Numerical Values

see if Stores column has values less than 1
see if Dept column has values less than 1
see if Weekly_Sales column have values less then 0

In [39]:
#get count of how many values in Stores column are less than 1
intLessThanOne = (dfSales_Stores_DataSet_Work["Store"] < 1).sum()
#print result
intLessThanOne

np.int64(0)

---

## Observations - Sales_Stores_DataSet

Values for Store in acceptable limits

## Validate Size Values

In [40]:
#get count of how many values in Size column are less than 1
intLessThanOne = (dfSales_Stores_DataSet_Work["Size"] < 1).sum()
#print result
intLessThanOne

np.int64(0)

## Observations - Sales_Stores_DataSet

Values for Size in acceptable limits

## Data Transformations/Feature Engineering

Create column: StoreType as integer mapped from existing Type column
i.e. have 1, 2, 3 values instead of Type columns values A, B, C

In [ ]:
#create column:StoreType as integer (Copilot suggested code)
#left as, is would prefer proper naming convention: dictTypeMapping

type_mapping = {"A": 1, "B": 2, "C": 3} 
dfSales_Stores_DataSet_Work["StoreType"] = dfSales_Stores_DataSet_Work["Type"].map(type_mapping).astype("int64")

#check results get first 50 rows
dfSales_Stores_DataSet_Work.head(50)

   Store Type    Size  StoreType
0      1    A  151315          1
1      2    A  202307          1
2      3    B   37392          2
3      4    A  205863          1
4      5    B   34875          2

## Observations - Sales_Stores_DataSet

Column created successfully, data looks good

## Check Data Type For New Column Is Correct

In [45]:
#get schema data types
dfSales_Stores_DataSet_Work.dtypes

Store        int64
Type           str
Size         int64
StoreType    int64
dtype: object

## Observations - Sales_DataSet

Data type for new column StoreType is correct

## Remove Unnecessary Columns

In [ ]:
#nothing to do as no viable columns to remove!

## Observations - Sales_Stores_DataSet

Column created sucessfully, data looks good

## Save Work DataFrame To CSV File

In [ ]:
#create list of columns new and old JUST what is actually needed
lstColumns = [
                #original columns
                "Store","Size",
                #new columns
                "StoreType"
              ]

#create new DataFrame for cleaned data
dfCleaned = dfSales_Stores_DataSet_Work[lstColumns].copy()

#save dfSales_DataSet_Work
dfCleaned.to_csv(strCurrentDir + CNST_STR_CLEANFILEPATH)

# Conclusions and Next Steps